- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/UserCard.tsx
close #
- UserCard 컴포넌트 생성 및 UI구현
- 3개의 props (userImage, userImageFallbackDealy, rank)를 받아 뿌려줍니다
- UserCard에서 User라는 도메인 제거 후 Card로 만들면, 조금 더 쓰임새가 있지 않을까 고민중입니다...(게임 대기방에서도 활용가능?)
아니면 모양을 맞춰보는 것도 좋아보입니다
- 유저의 게임 데이터가 없을때 랭크가 없을까요? 아니면 0위 이렇게 표현하는게 좋을까용?
> [Style] 메인화면 - 로비(메인페이지) 내부 UserCard 컴포넌트

- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomInfo.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserList.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/GameWaitingRoom/WsError.tsx
- src/pages/GamePage/constants.ts
- src/utils/checkEmptyObj.ts
- src/ws/endpoint.ts
- src/ws/types/wsResType.ts
close #
- GamePage 렌더링시(useEffect) 웹소켓에 연결하도록 했습니다
- 현재, 이전 메인페이지 화면에 연결되있지는 않아서 postman을 사용하여 따로 생성/입장 REST요청을 보내야합니다.
- 구독한 채널로부터 받은 응답을 GameWaitingRoom에 넘겨줍니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/ccd025be-f86e-4d16-b66f-c5fe6f2c8cbb
* 웹소켓 연결부 호출을 GamePage 로 두었는데 따로 훅을 두는게 나을까요?
---
** -# 40- 브랜치로부터 분기해서 PR base를 해당 브랜치로 두었습니다!
> [Feat] 게임룸 웹소켓 - 다른 유저 참여시 기존 모든 유저들의 목록 갱신

- package.json
- src/common/Backward/Backward.tsx
- src/common/Header/Header.tsx
- src/generated/.openapi-generator/FILES
- src/generated/api.ts
- src/pages/GamePage/DisconnectModal.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameReadyAndStart.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomInfo.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserList.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- yarn.lock
close #
- 유저의 상태(방장 유무, 준비 유무)를 웹소켓서버로 전송, 응답 합니다
- 방 나가기 시 alert 모달 확인 후 화면 이동합니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/13b7021a-03cd-42f7-8939-12aeed3b6b60
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/c7d5d818-06ed-4a27-89c1-02f03ca8e623
* 2c64d84e8fe544eb7d326f9b7b80e8f4b8bfd496 StompClienet를 useRef로 두어서 초기값인 null값이 허용되더라구요, 프롭스로 넘길때마다 타입을 `| null` 처리해야되는데, 다른 방법이 있을까요? 매번 if (ws) { ..} 처럼 가드를 하는게 더 번잡해진다고 느껴서 이렇게 처리했습니다.
* 뒤로가기(< Backward >)로 인게임을 나갈 경우에도 /main으로 라우팅을 하는데, useNavigate를 사용하기 때문에 새로고침이 발생하지 않아서 웹소켓 연결이 끊기지 않았습니다. 그래서 강제로 `window.location.reload()`를 사용했는데, 다른 방법이 있을까요?   useEffect 클린업 함수도 사용해보았는데, 접속자 모두가 연결이 끊겨서 방이 사라지는 문제가 생겼습니다. 같이 확인해봐도 좋겠네욥
---
TODO
> [Feat] 유저 준비 상태 반영, 방장 표기

- src/hooks/useEnterGameRoom.ts
- src/pages/MainPage/CreateRoom/CreateRoomForm.tsx
- src/pages/MainPage/EnterRoomErrorFallback.tsx
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/GameRoonListItem.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/PrivateRoomModal.tsx
- src/store/useRoomIdStore.ts
close #58 
- 방입장하는 기능을 구현했습니다.
- 비공개방, 공개방 나눠서 구현했습니다.
- 비밀번호가 일치하지 않을시 입장 막아뒀습니다.
- PrivateModal에 react-hook-form을 적용해두었습니다.
- 게임 입장 플로우를 보기위하여 리팩토링을 전혀 하지 못한상태입니다. 양해부탁드립니다..!!
- GameRoomList, PrivateModal, GameRoomListItem이 강하게 결합되어있습니다. 이를 어떻게 뗄지...감이안옵니다...
1. PrviateModal과 GameRoomListItem은 GameRoomList의 자식입니다
2. 둘 다 mutation을 씁니다. but, onSuccess시 로직이 약간 다릅니다. => 프롭스로 내려주어야 할까요?
3. 둘 다 zustand Store를 업데이트합니다. => 프롭스로 내려주어야할까요?
실제 상태와 연관이 있으니, props로 전달해도 무방할까요?
컴포넌트 분리도 걱정입니다..ㅎㅎ
> [Feat] 방 입장 기능 구현

- src/App.tsx
- src/common/AuthRoute/AuthRoute.tsx
- src/hooks/useAuth.tsx
- src/main.tsx
close #68 
- 라우팅마다 인증로직을 호출하는 컴포넌트를 만들었습니다 (AuthRoute)
- 인증된유저인지 확인하는 함수는 getMyProfile을 한번 래핑한 useAuth입니다
- **로그인한 유저만 갈 수 있는 페이지,** **로그인 한 유저는 갈 수 없는 페이지** 두개로 나뉘었습니다
AuthRoute에서 pathname을 호출하는게 맞나 싶습니다...!
그리고 찾아보니 private route같은 기능은 react-router-dom 6.4v에서 beforeloader같은 기능으로 정식출시 된다네요ㅎㅎ
> [Feat] 라우팅별 인증 기능

- src/hooks/useAuth.tsx
close #77 
-useAuthCheck가 데이터타입이 아닌 promise타입을 리턴하던 버그 수정하였습니다(죄송합니다...!!)
> [Fix] useAuthCheck 리턴 데이터 타입 수정(긴급!)

- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserList.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
- src/pages/GamePage/IngameWSErrorBoundary.tsx
- src/pages/GamePage/hooks/useIngameWebsocket.ts
- src/pages/GamePage/hooks/useToken.ts
- src/pages/GamePage/hooks/useWebsocket.ts
- src/utils/getToken.ts
close #
- 웹소켓 훅에서 token을 받아 헤더만드는 로직을 훅으로 분리했습니다.
-> 🤔 훅일필요는 없을까요? connectHeaders라는 객체를 반환하는 함수로 해도 될까요?
- 게임이 시작되어 교체되는 인게임 컴포넌트 리턴 부분을 에러바운더리로 감쌌습니다. 
-> 🤔 알맞은 방법일까요!
-> 🤔 연결이 잘못되거나 네트워크 등 예상 못한 에러 처리를 할 수있는거라고 생각했는데, 맞을까요 ?
- **useIngameWebsocket으로 부터 publishIngame 함수만 리턴**받습니다. 여기에 게임 별 엔드포인트를 destionation인자로 보내면됩니다! roomId까지 함수 안에서 가지기 때문에 /info, /round-finish 만 보내면 됩니다!!
> [Refactor] websocket 훅, 에러바운더리

- src/common/Ingame/IngameHeader.tsx
- src/pages/GamePage/IngameWSErrorBoundary.tsx
- src/pages/GamePage/common/DisconnectModal.tsx
close #102 
- 인게임 헤더에 더미데이터 대신 useRoomInfoStore에 저장한 roomInfo 값을 넘깁니다
> [Feat] 인게임 헤더

- src/apis/api.ts
- src/common/AuthRoute/AuthRoute.tsx
- src/common/Header/Header.tsx
- src/hooks/useAuth.tsx
- src/main.tsx
- src/pages/KaKaoLoginPage/KaKaoLoginPage.tsx
- src/pages/KaKaoLoginPage/kakaoAuthApi.ts
- src/pages/LoginPage/LoginPage.tsx
- src/pages/LoginPage/OAuth.ts
close #56 
- 카카오 소셜 로그인을 구현했습니다
- 카카오 로그인 버튼 클릭 => 로그인 과정 진행 => 로그인 성공 시 토큰 LocalStorage에 저장 후 `/main`으로 이동하도록 구현
- AuthRoute에 Redirect URI(/login/oauth2/code/kakao) 추가 했습니다
- #105  버그 리포트와 같이 에러가 발생하는데 어떻게 해결하면 좋을까요??
> [Feat] 카카오 소셜 로그인

- src/common/Ingame/IngameHeader.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
- src/pages/GamePage/GameWord/WordCell.tsx
- src/pages/GamePage/IngameWSErrorBoundary.tsx
- src/pages/GamePage/common/DisconnectModal.tsx
- src/pages/GamePage/types/websocketType.ts
- src/store/useWordsStore.ts
close #
- ingameRoomRes.questions로 100개의 단어를 보여줍니다. store에 저장합니다.
- 존재하는 단어 입력시 발행하고. 모든 참여자는 INFO타입 메세지를 받습니다.
- INFO타입 메세지의 submittedWord로부터 store를 갱신합니다.
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/fabc2821-d7d0-4f8e-9b8c-508e8c3cbc4b
* 이외 단어게임 진행로직 상에 필요한 부분들이 더 있을까요?
> [Feat] 단어 게임 - 발행, 응답 연결

- src/common/Ingame/Dashboard.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameSentence/useTypingState.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
- src/pages/GamePage/GameWord/GameWordContainer.tsx
- src/pages/GamePage/GameWord/WordGameLayout.tsx
- src/pages/GamePage/GameWord/WordRankContainer.tsx
- src/pages/GamePage/types/websocketType.ts
close #135 
- 단어게임에서 타수는 `현재 입력창에 입력한 글자 수 / 경과시간` 입니다.
- 단어게임에서 정확도는 `성공한 발행(단어입력후submit) 수 / 전체 발행 수`입니다.
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/ea3bf1af-d7f8-4ea4-bc64-720c19f28b93
* useTypingState의  onInputChange 프롭스인 totalChar 타입선언을 변경하지 않으려고, [단어 입력 Input의 onChange에선]() 임의로 100이라는 값을 인자로 넘기고 있습니다. 다른 방법이 있을까요?
* 타수, 정확도 계산에 더 나은 수식이 있다면 알려주세요!
* calculatedTypingSpeed 계산에 **200**을 곱하는 수식이다 보니 1 ~2초안에 4 ~6글자를 치는 단어게임에선 몇천타까지 나올수가 있네요..
* 타수나 정확도 부분에 이슈 확인되시면 알려주세요
> [Feat] 인게임 - 단어 대시보드 연결 값 수정

- src/common/Ingame/IngameHeader.tsx
- src/pages/GamePage/GameCode/CodeContainer.tsx
- src/pages/GamePage/GameCode/CodeForm.tsx
- src/pages/GamePage/GameCode/CodeFormContainer.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
close #134 #109 
- 게임 시작시 현재 라운드 및 실제 문제를 연결합니다
- 다음 라운드가 시작되면 새로운 문제를 보여줍니다. 
- 모든 유저가 입력을 다 하거나, 시간이 종료되면 라운드가 종료됩니다. 
- 모든 라운드가 끝나면 인게임 종합 랭킹을 보여줍니다.
useMemo, useCallback, useEffect, useRef를 완벽하게 이해하지 않고 사용해서 각종 에러가 발생했었습니다....
1. 엔터 키 입력하면 점수가 0점으로 초기화 되서 더해지는 에러 
> handleActiveEnter와 handleUpdateScore의 useCallback의 의존성 배열 다 채워서 해결
2. CodeFormContainer에 useEffect로 라운드가 끝났을 때 round-finish 발행하는 로직을 두니까 라운드가 끝나면 무한 발행하는 에러.. 
> GameCode로 라운드 끝났을 때 round-finish 발행하는 로직(handleRoundFinish)을 두고 props로 전달해서 해결
3. useRef로 convertedCode 만들어서 CodeFormContainer, CodeForm 둘 다 리렌더링이 바로 안되는 에러.. 
> CodeFormContainer, CodeForm에 key 값을 전달해서 해결 
코드가 현재 매우 지저분해서 정리할 필요가 느껴집니다.. 많은 조언 부탁드리겠습니다 🫠
GameSentence의 로직과 매우 유사하여 어느 정도 리팩토링을 통해 정리가 가능할 것 같습니다 👍
> [Feat] 인게임 코드 - 마무리

- src/pages/MainPage/MainPage.tsx
- src/pages/RankPage/RankPage.tsx
close #165 
- 메인화면에서 랭킹 페이지 연결
- 랭킹 페이지에서 활성화된 탭에 색상 추가
> [Feat] 랭킹 페이지 연결

- src/hooks/useOnlineUsers.tsx
close #181 
- 실시간 접속자 수를 15초마다 주기적으로 refetching 합니다(서버는 20초 단위)
> [Fix] 실시간 접속자수 실시간 폴링

- src/common/AuthRoute/AuthRoute.tsx
- src/common/Header/Header.tsx
- src/generated/api.ts
- src/hooks/useAuth/constants.ts
- src/hooks/useAuth/useAuth.tsx
- src/main.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/KaKaoLoginPage/KaKaoLoginPage.tsx
- src/pages/MainPage/DefaultErrorFallback.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/UserCard.tsx
- src/pages/MainPage/UserList.tsx
- src/pages/StartPage/StartPage.tsx
close #188
- useAuthCheck에 캐싱 10분 넣어두었습니다. 닉네임 변경시 꼭 `invalidateQueries`해주셔야 합니다!!
- 현재 접속중인 유저 목록에서 본인을 확인할 수 있게 표시하였습니다.
- 유저 프로필과 실제 데이터를 연동하였습니다.
게스트 유저가 순위표에 마우스 hover하면, '로그인 하셔서 기록을 남겨보세요!' 같은 카드가 프로필을 가리게 하고싶은데 어떻게 생각하시나요? (누르면 로그인 화면으로 이동ㅎㅎ)
> [Feat] useAuthCheck 캐싱 추가, 온라인유저 본인 표시, 유저프로필 데이터 연동

- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomInfo.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/IngameWebsocketLayer.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
- src/pages/GamePage/hooks/useWebsocket.ts
- src/pages/RankPage/RankItem.tsx
- src/pages/RankPage/RankList.tsx
- src/pages/RankPage/RankPage.tsx
- src/pages/RankPage/types/convertedRankData.ts
- src/store/useGameWaitingRoomStore.ts
close #171 #199 
- 전체라운드 종료 -> 랭킹화면 -> 10초후에 게임룸으로 이동합니다.
- 10초후 이외에도 '메인 화면(로비)으로 나가기', '게임룸으로 나가기' 연결
- 라운드 종료 후 다시 게임 대기방으로 갈 수 있도록 하는 로직
- **GameFinish.tsx**
- 로직에 필요한 상태 등을 store에 최신화
- **useWebsocket.ts**
- 로직에 필요한 상태를 store에 추가
- **useGameWaitingRoomStore.ts**
- 추가한 상태에 따라 달라진 props 전달
- GamePage.tsx
- GameRoomInfo.tsx
- GameRoomUserItem.tsx
- GameWaitingRoom.tsx
- 게임 종료 후 랭킹에서 본인 순위 확인 기능 추가
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/671ef687-8842-4bde-8abe-b7875e1c151a
최대한 해봤는데 놓친 부분이 있을 수도 있고, 기능이 동작하도록 구현해서 부족한 부분이 있을 수 있습니다 ㅠㅠ 
놓친 부분이 있다면 바로 말씀해주세요!
* store에 있는 ingameRoomRes 의 type이 FINISH 임 → 준비 취소하고 다시 준비하고 게임 시작하면 GameFinish 컴포넌트가 매우 짧은 시간 렌더링 됨  → setIngameRoomRes ({} as I_ingameRoomRes) 로 해결
* store에 있는 allMembers의 readyStatus가 모두 true 임 → 시작 버튼이 …
> [Feat] 전체 라운드 종료 후 게임룸으로 이동

- src/common/Ingame/IngameHeader.tsx
- src/pages/RankPage/RankItem.tsx
close #204 
- 랭킹 점수 내림처리, IngameHeader내부 timer 리턴값 문자열로 사용
- 큰 변경은 없습니다!
> [Fix] 랭킹 점수 내림처리, IngameHeader내부 timer 리턴값 문자열로 사용

- src/common/Ingame/IngameHeader.tsx
- src/common/Timer/Timer.tsx
- src/hooks/useTimer.ts
- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GameSentence/GameFormContainer.tsx
- src/pages/GamePage/IngameWebsocketLayer.tsx
- src/pages/GamePage/common/RoundWaitModal.tsx
- src/store/useIngameStore.ts
close #176 
- 라운드 시작 전 카운트다운을 추가하였습니다.
- 이를 위하여 useTimer 로직을 변경하였습니다. (startTimer함수와 autoStart옵션 추가)
- 라운드 종료시 대기방이동 남은시간 ms표기에서 seconds로 변경하였습니다(영상에는 반영 안됨)
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/87127340/2a6d15ef-3dd5-4a5f-a9db-574e3066b9a5
- 급하게 만들어서 그런지 컴포넌트가 재사용성이 떨어지네요 ㅎㅎ 
- 대기시간은 얼마가 적절할까요?
- UI는 임시라서 조언 팍팍 부탁드립니다
> [Feat] 각 라운드별 대기시간 추가

- src/common/Ingame/IngameRank.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/store/useCarStore.ts
close #211 
- 유저 각각에 자동차 이미지 지정
- 인게임 랭킹에 반영
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/a542ffcc-308a-42a8-9cdb-66ef4b7d7201
게임룸에서 참여자 정보가 계속 바뀌다가 게임시작하는 시점의 최종 참여자를 가지고, { 유저번호 : 이미지인덱스} 의 배열 store를 저장하게 했습니다.
게임룸에서 저장 -> ingameRank에서 사용까지 props가 길어지는 것 같아서 store로 이용했는데 다른 방법이 있을까요
> [Fix] 인게임랭킹 유저-자동차 연결

- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/common/DisconnectModal.tsx
close #222 
- 게임방에서 본인에 대한 식별 기능 추가
- 나가기 클릭시 등장하는 모달 콘텐츠 z-index 변경 및 오버레이 z-index 추가
본인일 때 좀 더 구분을 잘할 수 있도록 하려면 어떻게 해야할까요? 🤔
색상을 임시로 추가해봤는데 좋은 아이디어 추천해주시면 감사하겠습니다!!
> [Feat] 게임방에서 본인에 대한 식별 추가

- src/hooks/useCreateGameRoom.ts
- src/hooks/useDebouncedMutation.ts
- src/pages/MainPage/CreateRoom/CreateRoomForm.tsx
close #99 
- useMutation을 래핑한 useDebounceMutation을 제작하였습니다.
- 디바운스 딜레이는 기본 0.2초 입니다!
- 방 생성 mutation후 응답 오기전까지 방 생성버튼을 disabled처리 하였습니다.
- 응답이 더 길면 답답할 것 같아서 0.2초로 하였는데 최적의 시간은 몇초일까용?
- 다른 mutation에는 버그 찾으면서 천천히 적용해보겠습니다..!!
> [Feat] mutation시 디바운스 기능 추가

- src/pages/MainPage/GameRoomList.tsx
close #229 
- 게임 방 목록 필터링 '전체' 에서 게임중인 방 목록 보이던 부분 수정하였습니다.
실수가 잦아져서 죄송합니다...😭
> [Fix] 게임 목록 '전체' 탭에서 게임중인 방 목록 안보이게 수정

- src/pages/GamePage/GameSentence/GameForm.tsx
close #232 
- 문장게임 띄어쓰기시 예시 문장에 글자가 있어서 틀렸지만, 점수가 올라가는 버그를 수정하였습니다.
**수정 전에는 점수가 올라 차량이 움직였습니다!**
SSOT를 지키지 않아서 로직에 헛점이 많네요..ㅠㅠ
> [Fix] 문장게임 오타 검출 로직 수정

- src/generated/api.ts
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
- src/pages/GamePage/hooks/useWebsocket.ts
- src/pages/GamePage/types/ingameTypes.ts
- src/pages/GamePage/types/trackType.ts
- src/pages/GamePage/types/websocketType.ts
- src/store/useCarStore.ts
- src/store/useIngameStore.ts
close #225 
- 인게임 중 유저 이탈시 해당 유저의 자동차 바로 제거
-> 게임룸에 EXIT 응답시 ingameRoomRes를 업데이트 합니다 -> zustand setter 함수 타입을 변경했습니다.
- 게임룸에서부터 배정받은 memberId-자동차 이미지 쌍 (carImgStore)을 인게임 트랙에서도 유지합니다 
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/fd34d1ab-bd85-4879-889d-ce4ba511525a
추가 예외사항 발견하시면 알려주세요..
시작위치 위에서부터 
1
2
순으로 게임을 시작했다가 1번유저가  2번유저가 윗층(y좌표상 위쪽)으로 이동됩니다.. 추가 PR에서 수정하겠습니다.
> [Fix] 이탈 유저 인게임 트랙에서 반영

- src/pages/MainPage/MainPage.tsx
- src/store/useRoomInfoStore.ts
close #244 
- 인게임 도중 이탈하여 /main에 온경우 선택한방이 없으므로 roomInfo를 초기화합니다.
* 모달 내부에서 처리하려고 하니까 roomInfo를 받아오고 set하는게 겹쳐서 조건이 많아지더라구요, 그래서 main에서 처리해보았습니다.
> [Fix] 인게임 이탈시 roomInfo 초기화

- src/pages/GamePage/IngameWebsocketLayer.tsx
close #249 
- 2라운드 이후 타이머가 돌아가지 않는 버그를 수정하였습니다
- `useEffect` 의존성 배열에 `ingameRoomRes.type`이 들어가있는데, 전원 입력하지 않을시 2라운드부터 `NEXT_ROUND_START`만 들어오기 때문에 `isRoundWaiting`이 업데이트되지 않아서 타이머가 돌아가지 않았었습니다
> [Fix] 아무도 타이핑하지 않을시 2라운드 후 타이머 돌아가지 않는 버그 수정

- src/common/Ingame/IngameHeader.tsx
- tailwind.config.js
close # 221
- 라운드 종료 5초전부터 타이머가 깜빡입니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/81412212/877c940a-402e-4c7b-8ac0-1ccafd209244
* 색상, 몇초후부터 깜빡일지
> [Style] 라운드 종료 5초 전부터 타이머 깜빡임

- src/common/Header/Header.tsx
- src/common/Layout/BodyLayout.tsx
- src/pages/GamePage/GameCode/CodeForm.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
- src/pages/GamePage/common/TrackLine.tsx
- src/pages/MainPage/CreateRoom/CreateRoomForm.tsx
close # 221
- 방 생성 모달에서 방입장 제한 인원 기존 2인에서 **8인**으로 수정하였습니다.
- 자동차 트랙 좌표 수정 -> 이미지는 128x128인데 그 중 실제 자동차가 정사각형 꽉차게 들어가 있는게 아니다보니 위치마다 조정이 필요했습니다.
- 코드 게임에서 , 알맞게 입력인 경우 bold처리가 되면서 주어진 문제와 입력창 글자크기 및 자간이 바뀌고 있었습니다. -> **bold 처리 삭제**  ( bold처리 필요하시면, 문제 문장 전체랑 입력창 전체에도 처리해주시면 될거같습니다
bold처리 모두 제외했습니다.  있는게 낫다면, 입력창까지 모두에게 bold처리를 해줘야 할것 같습니다.
> [Style] 자동차 트랙 위 좌표수정 및 스타일링 수정

- src/common/Header/Header.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameReadyAndStart.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomLinkInvitation.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- tailwind.config.js
close #
시작 버튼
- 모두가 준비 되면 네온 효과 유지
- 모두가 준비 아니면 네온 효과 역으로 재생
준비 버튼
- 준비 버튼 누르면 slice 효과
- 다시 눌러서 취소 되면 효과 역으로 재생
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/94d604cd-9530-48b7-851e-2e6589f292cc
> [Fix] UI 개선 - GamePage

- src/common/Error/ErrorBoundaryFallback.tsx
- src/main.tsx
- src/pages/GamePage/GamePage.tsx
close #259
- gamePage, ingame 에서 새로고침시 main으로 라우트 시킵니다
TODO: 리렌더링 트리거 방법 더 고민..
> [Feat] 웹소켓 연결 후 새로고침 시 /main 라우팅

- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
- src/pages/GamePage/types/ingameTypes.ts
- src/store/useCarStore.ts
close #243 #266 
- 유저 이탈시 자동차트랙상위치(y좌표)를 유지합니다
-> 게임 시작시의 유저 목록을 가져서 인덱스로 사용했습니다 
- 100점이후에도 그 전처럼 트랙을 계속해서 이동합니다. (화면에서 사라지던 이슈 해결)
(흐름 요약)
인게임 시작할때 초기 유저 전체를 저장 `originUsers`
{유저아이디 : 점수} 쌍의 `idScore` 저장 ->(변하지않은 차 다시 그리지 않기 위함인데 추후 수정 예정
프롭스로 넘어오는 응답값인 allMembers를 돌면서 carsRef[memberId] 에 좌표 계산
좌표로 자동차 그림
나간 유저의 차를 그리지 않기 위해 EXIT를 감지해서 allMembers에서 해당 유저를 지웠었는데,, 트랙상 좌표 유지를 고민하다 보니 나간 멤버도 있으면 더 편했겠다는 생각이 들었네요.... @_@
타입이랑 코드가 정리가 많이 안되어있는데,, 코드 정리와 최적화를 고민하여 리팩토링하겠습니다._빠른시일내로.._
> [Fix] 자동차 좌표 이슈들 해결

- src/common/Header/Header.tsx
- src/common/Header/utils/exchangeVolumeState.ts
- src/pages/NicknamePage/NicknamePage.tsx
- src/pages/NicknamePage/UpdateNickname/UpdateNicknameForm.tsx
- src/pages/StartPage/StartPage.tsx
- src/store/useVolumeStore.ts
close #251 
- 로그인(게스트, 소셜) 후 audio play를 위해 상태 관리를 zustand로 했습니다
- 헤더 아이콘에 볼륨 조절 아이콘만으로 음량 조절이 가능할거 같아서 play 아이콘을 지웠습니다!
- play 아이콘을 지워도 괜찮을까요??
- 지금 StartPage에서 게스트 로그인 or 소셜 로그인을 성공하면 음악이 재생되도록 수정했는데 어떠신가요??
> [FIX] 헤더 버그 수정

- src/pages/MainPage/MainPage.tsx
close #261 
- 게임페이지에서 didAdminStart를 초기화합니다.
브라우저 뒤로가기로 main으로 온 상황에 didAdminStart가 계속 true인게 문제였습니다.🫠
> [Fix]: 브라우저 뒤로가기로 나간후 방 입장, 생성 이슈 해결

- src/apis/api.ts
- src/common/AuthRoute/AuthRoute.tsx
- src/common/Header/Header.tsx
- src/hooks/useAuth/useAuth.tsx
- src/hooks/useUpdateNickname.ts
- src/pages/MainPage/MainPage.tsx
- src/pages/NicknamePage/NicknamePage.tsx
- src/pages/NicknamePage/UpdateNickname/UpdateNicknameForm.tsx
- src/pages/NicknamePage/UpdateNickname/UpdateNicknameModal.tsx
close #273 
- UpdateNicknameModal, Form을 재사용 가능하도록 코드를 수정했습니다
- 기존에 리렌더링되는 버그를 수정했습니다.
- 게스트 로그인 상태에서 게스트 로그아웃 후 카카오 로그인하는 로직 추가
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/44563138/aed1b147-da94-404b-80c2-d176dc061ab8
- 버그 수정안된 부분있으면 피드백해주세요!!
> [FIX] 닉네임 업데이트 버그 수정

- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GameFinish/sortScore.test.ts
- src/pages/GamePage/GameFinish/sortScore.ts
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/constants.ts
- src/pages/RankPage/RankList.tsx
close #286 
- 공동 등수 산정 로직 수정
- 문장당 입력 시간 5초로 변경
- 인게임랭킹에서 시상대 삭제
_마무리다보니,, 한브랜치에 작업을 한번에 하게되었습니다.._
> [Fix] 동점자 순위, 문장당5초, 인게임랭킹 스타일수정

- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/RankPage/RankPage.tsx
close #
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/a63941b4-23d1-4867-954f-d7ef863c7a42
> [Style] 일관된 UI, UX 개선

- package.json
- src/common/Spinner/Spinner.tsx
- src/main.tsx
- src/pages/GamePage/IngameWebsocketLayer.tsx
- vite.config.ts
close #290 
- 번들링 최적화를 위하여 code splitting을 통해 청크사이즈를 줄였습니다.
- 첫 렌더링시 필요한 컴포넌트를 제외한 컴포넌트 중 사이즈가 큰 컴포넌트를 `React.lazy`를 사용하여 비동기 렌더링을 하였습니다.
- `React.lazy`로 불러오는 컴포넌트는 비동기렌더링이기에 `Suspense`로 감싸서 UX를 개선하였습니다
- Spinner컴포넌트의 props를 수정하였습니다. 또한 기본 스타일을 추가하였습니다(`absolute top-1/2 left-1/2`)
- 각 청크에서 공통으로 쓰이는 모듈을 `vendor`로 분리하였습니다.
각  게임 컴포넌트 내부에서 동적 import로 청크사이즈를 더 줄이려다가, 게임 컴포넌트가 렌더링될땐 내부 모듈을 한번에 불러와야 할 것 같아 줄이지 않았습니다. 맞는 판단일까용?
> [Fix] 번들링 최적화 - code split

- src/pages/MainPage/GameRoomList.tsx
close #x
- 방 목록 넘칠시 레이아웃 깨짐을 수정하였습니다
- 임시로 스크롤 바를 부착하였습니다(영재님의 의견 반영)
> [Style] 방 목록 넘칠시 레이아웃 깨짐 수정 (긴...급...) 🚨 

- src/pages/RankPage/RankList.tsx
close #
- 유저가 많아져서 랭킹이 화면 넘어감에 스크롤 처리했습니다
> [Style] 랭킹 스크롤 넘칠시 레이아웃 깨짐 수정 (긴...급...) 🚨2

- src/hooks/useEnterGameRoom.ts
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/GameRoonListItem.tsx
close #x
- 게임중인 방 목록 노출하게 수정하였습니다.
- 게임중인 방, 대기중인 방을 구분하는 UI를 추가하였습니다.
- 방 입장 후 에러메시지 반환시 Toast로 출력하게 변경하였습니다.
maxRound도 보이게 추가하면 좋을까요?
> [Style] 게임중인 방 목록 UI 추가

- .github/workflows/buildTest.yaml
- .github/workflows/deploy.yaml
- .husky/pre-commit
close #312 
- `main`브랜치에 **push**시 자동배포하는 git actions를 추가하였습니다. 세부단계는 아래와 같습니다.
1. 브랜치를 복제합니다(checkout)
2. Node v20을 설치합니다
3. yarn v4를 사용하기위하여 corepack을 enable상태로 변경합니다
4. yarn 버전을 현재 저희 개발환경에서 사용중인 4.1.0으로 변경합니다
5. 의존성을 설치합니다
6. 빌드
7. aws 인증정보를 셋팅합니다
8. aws에 배포합니다. s3의 `assets` 폴더내부 파일을 재귀적으로 삭제 후 s3버킷에 현재 git actions 컨테이너의 `./dist` 파일과 동기화합니다.
9. cloudfront의 캐시를 무효화합니다(전부 무효)
- vercel 배포에 비하여 총 배포시간 약 20%내외 감소하였습니다.
- `main`브랜치에 **pr**시 build + test함수 검사하는 git actions를 추가하였습니다
-  이제 `package.json`내부 `packageManager`프로퍼티 추가 및 **lint-staged + husky** 정상작동 합니다
1. yarn v4의 zero install 활용방안(경로문제...😐)
2. yarn 캐싱 이용방안
> [Feat] CI용 git actions 추가

- package.json
- src/pages/GamePage/GameCode/CodeForm.tsx
- src/pages/GamePage/GameCode/CodeFormContainer.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameSentence/GameForm.tsx
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
- src/pages/GamePage/GameWord/WordGameLayout.tsx
- src/pages/GamePage/hooks/useFocusInput.ts
close #302 
- useFocusInput 훅에 인자로 조건 값(isFocus)을 넘겨서 다른 input에서도 쓸 수 있게 만들었습니다.
- 문장, 코드, 단어 게임에서 input에 focus 하기 위한 조건 값 : isRoundWaiting 
- 다른 div나 button 엘리먼트 등에서도 사용할 수 있게 만들어보려고 했는데 타입 문제 때문에 실패했습니다.
- [참고한 자료](https://velog.io/@apparatus1/Typescript-useRef-%EC%9D%BD%EA%B8%B0-%EC%A0%84%EC%9A%A9-%EC%97%90%EB%9F%AC)
- type이 mutableRef 여야함 (focusElement.current에 값을 넣기 위해서)
- <img width="228" alt="스크린샷 2024-03-29 오전 12 03 19" src="https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/da2b69f4-f3c6-4540-951a-6b5365c59063">
- button 이나 div 엘리먼트는 type이 LegacyRef라 mutableRef를 할당할 수 없음
??????
> [Refactor]: useFocusInput 다른 input에서도 쓸 수 있도록 변경

- src/pages/GamePage/hooks/useWebsocket.ts
close #308 
- 연속적으로 게임 진행시 인게임웹소켓 구독이 중첩되는 것을 방지하도록 수정했습니다.
- [StompJs 공식문서](https://stomp-js.github.io/api-docs/latest/classes/Client.html#unsubscribe)를 참조해서 인게임이 종료되면  unsubscribe을 하도록 구현
* 현재 게임을 연속으로 해도 더이상 중첩되지 않습니다.
> [FIX]: 인게임 구독 중첩 안되도록 수정
