Team-E2I4/Team-E2I4-TiKiTaza-FE

- src/main.tsx
- src/pages/GameFinishPage/GameFinishPage.tsx
- src/pages/RankPage/RankData.ts
- src/pages/RankPage/RankPage.tsx
close #21 
- css 만을 사용해서 순위 UI를 구현했습니다
- `RankList` 컴포넌트를 이용하여 순위표를 작성했습니다.
- `assets` 폴더로 `login` `rank` 이미지를 이동했습니다.
- 저희가 디자인할 때부터 고민이 많았던 1,2,3등 순위 UI가 조금 허전한거 같습니다.. 추후에 유저 프로필 이미지를 추가하면 괜찮아 질까요?
- 색상 조합은 어떤지 피드백 부탁드립니다
> [Style] GameFinishPage UI 구현

- src/apis/api.ts
close #62 
- api생성시 토큰 넣던 버그를 호출시 토큰 넣게 변경하였습니다
> [Fix] api 호출시 토큰 안들어가는 버그 수정(긴급)

- src/main.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/GameWaitingRoom/hooks/useWebsocket.ts
- src/utils/checkEmptyObj.ts
- src/utils/checkIsEmptyObj.ts
- yarn.lock
close #64 
- 메인페이지에서 방입장시 저장한 store를 꺼내서 게임방에서 사용합니다. 웹소켓연결시에도 사용합니다.
- roomId가 잘못된경우(null)와 구독 응답response가 잘못된 경우를 상태 isWsError로 가져서 리턴합니다
* 또 발생할 수 있는 에러 상황이 어떤게 있을까요?
* roomId가 잘못된 값인 경우 혹은 초기 null인 경우에 대응하기 위해 이렇게 처리했는데.. 개선방법 알려주시면 감사하겠습니다.
--> SSE에서하신거처럼 커스텀 에러바운더리를 둘까요?
> roomId store 사용, useWebsocket 에러 리턴

- src/App.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserList.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/GameWaitingRoom/hooks/useWebsocket.ts
close #74 
로그인 인증 로직을 게임페이지에 반영
- 게임페이지 내 로그인요청 제거
- 저장된 userId 사용
<br/>
.. 커밋 위 두개는 local-origin 버전 다른데 Rebase 잘못한 이슈로 수정,재수정 된 커밋입니다..죄송합니다🥹
> [Feat] 로그인 인증 로직을 게임페이지에 반영

- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameWaitingRoom/GameReadyAndStart.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserItem.tsx
- src/pages/GamePage/GameWaitingRoom/GameRoomUserList.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/GameWaitingRoom/hooks/useWebsocket.ts
- src/pages/GamePage/types/websocketType.ts
close #69 
close #79 
- 게임방의 Id를 zustand의 store로 받아오는 기능
- 유저 강퇴 기능
- 게임 시작 기능
- 유저 강퇴
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/5b6e09ad-cee2-4805-a526-45b9721e0f85
- 게임 시작은 컴포넌트 렌더링을 잘 하고 있습니다!
> [Feat] 게임방 페이지 - 유저 강퇴 기능 ,게임 시작 기능

- src/common/Header/Header.tsx
- src/common/Ingame/Dashboard.tsx
- src/common/Ingame/IngameHeader.tsx
- src/common/Ingame/IngameRank.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
close #
- GameCode 에 Input 추가 및 z-index 수정
- 인게임 UI 스타일링 소소하게 수정했습니다.
UI 아이디어, 수정사항 뭐든지 언제든지 [이슈](https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/issues/82)에  추가해주세여~!
> [Style] 인게임 UI 스타일링 수정

- .github/ISSUE_TEMPLATE/bug_report.md
add bug report template in issue
- 버그리포트 추가하였습니다
> [Docs] 버그리포트 이슈템플릿 추가

- src/hooks/useEnterGameRoom.ts
- src/pages/MainPage/EnterRoomErrorFallback.tsx
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/GameRoonListItem.tsx
- src/pages/MainPage/PrivateRoomModal.tsx
close #89 
- PrivateModal, GameRoomListItem 렌더링 구조를 리팩터링 하였습니다.
- Item내부에서 mutation을 가져오지 않고 list에서 가져온 뒤 props로 넘겨주는게 맞을까요?
- 컴포넌트를 재사용하려면 어떻게 해야할까요...?🤔
> [Refactor] Private - GameRoomListItem 렌더링 구조 리팩터링

- src/common/Timer/Timer.tsx
close #106 
- 인게임에서 사용하는 타이머를 구현했습니다
- props를 지정해서 타이머를 사용할 수 있습니다
- minutes: 분
- seconds: 초
- onFinishRound: 라운드가 끝날때 진행되는 로직
- 분/초 를 MS(밀리세컨드) 변환하여 타이머를 측정하고 다시 분/초 단위로 변경하도록 구현했습니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/44563138/200e1ec1-75e4-42dd-97a6-6fd0147db0dc
용량 문제로 3초로 지정해서 영상을 올렸습니다
- 타이머를 인게임에서 적용할 때 약간의 수정이 필요할거 같습니다
- 더 좋은 방식이 있다면 추천 부탁드립니다!
> [Feat] 인게임 타이머 기능 구현

- src/pages/StartPage/StartPage.tsx
close #121 
- StartPage에 진입 시 토큰이 있을 경우 삭제하는 로직을 추가했습니다
- 아까 영현님이 말씀해주신 부분을 제가 이해를 제대로 한건지 궁금합니다..!
- 더 추가할 로직은 없을까요??
> [Feat]: StartPage에 진입시 토큰있으면 삭제하는 로직 추가

- src/apis/api.ts
- src/pages/GamePage/GameSentence/GameSentence.tsx
close #129 
- 문장게임 주석처리 삭제
- reissue요청시 헤더에서 액세스토큰 제거하여 요청
x
만약 reIssueAccessToken에서 에러가 발생하면, 어떻게 잡아야 할까용?
> [Fix] 토큰 재발급 로직 수정

- src/common/Timer/Timer.tsx
- src/common/Timer/constants/time.ts
- src/common/Timer/utils/convertTime.ts
- src/hooks/useTimer.ts
close #138 
- 라운드 남은시간을 초기화할 수 있는 로직 추가
- 타이머 로직을 훅으로 분리
- 남은 시간을 초기화하는 로직에서 라운드 시간으로 초기화했습니다..! 혹시 0초로 초기화해야할까요??
- 훅으로 분리해야할 부분이 더 있을까요??
> [Feat]: 타이머 로직 추가, 훅으로 분리

- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GamePage.tsx
close #140
- store중 roomInfo.gameMode 로 선택된 게임모드에 따라 각 게임화면으로 이동합니다.
* 이후에 zustand 혹은 ReactQuery 리팩토링 시 변경될 수 있습니다.
> [Feat] 선택된 게임모드 store에서 연결

- src/common/Ingame/IngameHeader.tsx
- src/generated/api.ts
- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
- src/pages/RankPage/RankList.tsx
close #143 
- 게임 종료시 GameFinish로 이동 및실제 데이터 연동하였습니다.
- 정해진 시간 뒤에 메인화면으로 이동합니다.
게임 flow한번 다 볼수 있게 되었습니다~
둘 다 머지되면 vercel로 배포하여 게임플로우 확인 후 리팩토링/버그/수정 작업진행하면 좋을 것 같아요
> [Feat] GameFinish 실제 데이터 연동 완료

- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
- src/pages/GamePage/GameWord/WordGameLayout.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
close #142
- 인원수별 타이머 시간 설정 -> 120/인원수 (초)
- 시간 종료시 다음라운드 발행
- 단어 모두 입력시 다음라운드 발행
> [Feat] 단어게임 마무리

- src/hooks/useSSE/index.ts
- src/main.tsx
close #148 
- EventSourcePolyfill사용시 타입오류 수정하였습니다. (이벤트 네이밍 이슈)
> [Fix] EventSourcePolyfill 타입 오류 수정

- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GamePage.tsx
close #151 
- GameSentence에서 전해주는 랭크데이터를 GameFinish에서 받는 타입으로 수정
- GamePage에서 사용하지 않는 Fragment import 제거
> [Fix] GameFinish, GamePage오류 수정

- index.html
- src/common/Ingame/IngameHeader.tsx
- src/pages/GamePage/GameCode/CodeContainer.tsx
- src/pages/GamePage/GameCode/CodeForm.tsx
- src/pages/GamePage/GameCode/CodeFormContainer.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/common/CanvasTrack.tsx
- src/pages/GamePage/hooks/init.ts
- src/pages/GamePage/hooks/useIngameWebsocket.ts
- src/pages/GamePage/hooks/useWebsocket.ts
- vite.config.ts
close #155 
- SockJS html script 태그에서 import문으로 수정
> [Fix] SockJS module

- vercel.json
close #159 
- vercel spa 새로고침 에러 수정하였습니다
> [Fix] Vercel SPA 새로고침 에러 수정

- src/apis/api.ts
- src/hooks/useOnlineUsers.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/UserList.tsx
close #163 
- 메인화면 좌측 실시간 접속자를 보여줍니다.
- 빠르게 구현만 완료하였습니다.
- 리팩토링하면서 필요하면 같이 진행하겠습니다
> [Feat] 현재 접속자 기능 추가

- src/pages/MainPage/SSEErrorBoundary.tsx
close #172 
- sse timeout 시간을 서버에맞게 1시간 => 60초로 변경하였습니다
> [Fix] sse Timeout 서버에 맞게 60초로 변경

- src/common/Timer/utils/convertTime.ts
- src/hooks/useTimer.ts
close #182 
- 타이머 단위 변경했습니다.
- `useTimer` 리턴 값을 String에서 Number로 수정했습니다
- `/src/common/Timer/utils/convertTime.ts` 경로에 있는 convertTime 함수를 사용해서 `mm:ss`와 `mm:ss:ff` 타이머 string 값을 리턴하도록 수정했습니다.
- 변수명이나 함수명 어색한 부분있다면 말씀해주세요!
- 혹시 수정 빠뜨린 부분있으면 말씀해주세요
> [Feat] Timer 수정

- src/common/Timer/utils/convertTime.ts
- src/hooks/useTimer.ts
close #197 
-  Timer를 이전과 같이 초 단위로 수정했습니다
- timeLeft를 이전과 다르게 Number로 수정해서 `mm:ss`로 사용하시려면 `covertTime` 함수를 사용하셔야 합니다!
> [Feat] Timer 이전으로 되돌리기

- src/pages/GamePage/GameCode/CodeForm.tsx
- src/pages/GamePage/GameCode/CodeFormContainer.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameSentence/GameForm.tsx
- src/pages/GamePage/GameSentence/GameFormContainer.tsx
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/common/RoundWaitModal.tsx
close #207 
- 문장, 코드게임 점수 로직 변경하였습니다(내림 => 올림 처리
- 마지막 업데이트시 100점으로 올라가게 하였던 부분 삭제.
**수정 전에는 4~50점대였습니다**
코드게임 렉 해결되면 테스트 해봐야할 것 같습니다..!! @dlsxjzld
> [Fix] 점수 로직 변경

- src/pages/GamePage/GameFinish/GameFinish.tsx
- src/pages/GamePage/GameWord/GameWord.tsx
- src/pages/GamePage/GameWord/WordGameLayout.tsx
- src/pages/GamePage/GameWord/WordRankContainer.tsx
- src/pages/GamePage/GameWord/WordRankTrack.tsx
- src/pages/GamePage/IngameWebsocketLayer.tsx
- src/pages/RankPage/RankItem.tsx
- src/pages/RankPage/RankList.tsx
close #202 
- 단어게임 동점자들 같은 순위로 산정
- 단어게임 트랙에서 본인 점수, 닉네임 표시
* ranking 부여하는 수식 맞는지 확인부탁드립니다 ㅎ...
> [Feat] 단어게임 순위 산정

- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/MainPage.tsx
close #201 
- 메인화면 상단에 게임 목록을 모드로 필터링 하는 버튼을 추가했습니다.
UI가 항상 고민이네요...!!
> [Feat] 게임 목록 필터링 기능 추가

- src/apis/api.ts
close #212 
- 게스트 유저의 아이디가 redis에서 삭제된 경우(토큰 재발급시 실패한 경우) 로컬스토리지에서 토큰을 삭제합니다.
일단 토큰 재발급시 에러를 받으면, 로컬스토리지에서 삭제 후 alert을 띄우게 해놨습니다.
모든 에러에 대응하기에는 시간이 촉박하네요..ㅜ.ㅜ
> [Feat] 게스트 유저 토큰 재발급 실패시 로컬스토리지 토큰 삭제

- src/pages/GamePage/GamePage.tsx
- src/pages/GamePage/hooks/useWebsocket.ts
close #216 
- 인게임 중 한 유저가 이탈할 시 다른 유저도 나가지는 버그 해결
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/dd390c5b-f5bc-4247-98fa-4199e61907af
링크 초대 시 게임 도중일 때는 못 들어오게 막는 방법을 다른 방법으로 해야할 것 같네요! 
ex) 링크 초대 버튼을 누르면 url이 나옴 -> 게임 시작을 누르면 해당 방의 링크 초대 url을 바꿔서 이전 링크 초대 url을 가진 유저는 못 들어오는 방법?!
좋은 방법 같이 고민해보면 좋을 것 같습니다!! 🤔
> [Fix]: 인게임 중 한 유저가 이탈할 시 방이 사라지는 버그 해결

- src/pages/MainPage/CreateRoom/CreateRoomForm.tsx
- src/pages/MainPage/CreateRoom/constants/createRoom.ts
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/MainPage.tsx
- src/types/gameMode.ts
close #219 
- 방 설정 수정시 모드 싱크가 안맞던 버그 수정하였습니다.
- src/types폴더 만든 뒤 gameMode관련 타입 하나 만들었습니다.
**현재 코드게임**
**설정 변경에서도 코드게임**
`'SENTENCE' | 'WORD' | 'CODE'` 타입 사용하시던곳은 src/types 에서 임포트해서 사용해주시면될 것 같습니다.!!
> [Fix] 방 수정 버그 fix

- src/common/Ingame/IngameHeader.tsx
- src/pages/GamePage/GameCode/CodeForm.tsx
- src/pages/GamePage/GameCode/CodeFormContainer.tsx
- src/pages/GamePage/GameCode/GameCode.tsx
- src/pages/GamePage/GameSentence/GameSentence.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/common/DisconnectModal.tsx
close #173 
좀 더 좋게 최적화를 할 수 있으면 좋을 것 같은데 더 좋은 아이디어가 생각나시면 말씀해주세요!!
> [Refactor] 코드 - 최적화 필요

- src/common/Ingame/IngameHeader.tsx
- src/pages/GamePage/common/RoundWaitModal.tsx
close #227 
- 카운트다운 및 타이머가 제대로 작동하지 않던 버그를 수정하였습니다.
렌더링 구조는 리팩토링이 필요해보이네요...😭
> [Fix] 타이머 버그 수정

- package.json
- src/common/Header/AudioPopover.tsx
- src/common/Header/AudioSlider.tsx
- src/common/Header/Header.tsx
- yarn.lock
close #164 
- Header에 있는 아이콘을 클릭하면 음악 재생, 볼륨 조절을 할 수 있는 기능을 구현했습니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/44563138/eb4da65d-c27b-420e-9a6f-0ca6dc6d0c3a
- BGM과 효과음 종류는 추후에 더 추가해도 좋을거 같습니다
- 더 추가해야할 기능이 있다면 말씀해주세요!!
- 브라우저 시작이나 새로고침한 후에 자동재생하는 기능은 코드로 구현할 수가 없을거 같습니다... 혹시 방법이 있다면 정보 공유 부탁드립니다!!😭😭
> [Feat] BGM, 효과음 기능 구현

- src/pages/GamePage/GameWaitingRoom/GameModeDescription.tsx
- src/pages/GamePage/GameWaitingRoom/GameModeInfo.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
- src/pages/GamePage/hooks/useWebsocket.ts
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/MainPage.tsx
close #
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/c3ceb932-8e02-4dba-a1bb-104c6dc42e6b
1. 게임모드 설명란의 텍스트 사이즈를 키웠는데 적절할까요?!
2. 전체 목록을 누르면 스크린샷 처럼 멘트를 고쳐봤는데 적절할까요?!
> [Fix] UI 개선 - 게임방 

- src/common/Input/Input.tsx
- src/pages/GamePage/GameSentence/GameForm.tsx
221번 이슈
- 문장게임 유저입력 글자 크기 변경
- 인풋 컴포넌트 props 구조 살짝 변경
> [Style] 문장게임 텍스트 크기 변경

- src/pages/GamePage/GameWaitingRoom/GameModeDescription.tsx
- src/pages/GamePage/GameWaitingRoom/GameWaitingRoom.tsx
close #
- 게임 모드 설명을 더 상세한 내용들로 변경했습니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/26159ec8-6f3e-4a51-9e9c-107d3d45af8a
글이 길어지면서 scroll로 보기가 힘들어서 hover시 밑으로 커지게 했는데 현재 페이지의 밑 부분으로 넘어가서 안 좋은 것 같습니다. 
1. hover시 div의 밑변은 고정되어 있고 div의 height가 위로 커지게(현재는 영상처럼 밑으로 커짐) 하고 싶은데 계속 실패했습니다. 혹시 아시는 분 계실까요??! 🤔
2. 1번 방법이 힘들다면 게임 모드 설명을 클릭하면 dialog가 뜨도록 하는 게 나을까요? 
3. 더 좋은 방법이 있다면 알려주시면 감사하겠습니다 ㅠㅠ
> [Fix]: 게임 모드 설명 수정

- src/index.css
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/GameRoonListItem.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/UserCard.tsx
- tailwind.config.js
close #없음
- 메인화면각 엘리먼트에 그림자를 추가하였습니다.
- 게임 방 목록 hover시 애니메이션 추가하였습니다.
- 손님 기본 프로필 이미지를 수정하였습니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/87127340/7023e434-2c15-4032-81bb-4c2091ad8e0c
녹색 테두리 대신 깔끔하게 녹색 배경으로 갈까 고민중입니다
> [Style] 메인페이지 스타일링

- src/index.css
- src/pages/GamePage/GameCode/CodeContainer.tsx
- src/pages/GamePage/GameWaitingRoom/GameModeDescription.tsx
close #
- highlight.js 적용된 코드 최적화
- 게임설명 모드 hover 상태 수정
- font 설정
font가 제대로 설정 된 건지 잘 모르겠습니다. 이렇게 하는 게 맞을까요? 
잘 아시는 분 계시다면 알려주시면 감사하겠습니다 ㅠㅠ
게임 모드 설명이 안 잘리는지 확인 한 번 부탁드리겠습니다!
> [Fix] 인게임 핫 픽스

- src/common/Layout/BodyLayout.tsx
- src/hooks/useEnterGameRoom.ts
- src/pages/MainPage/GameRoomList.tsx
- src/pages/MainPage/MainPage.tsx
close # 221
- 호버 , 그림자 등 스타일 수정
- 메인화면 방 목록에서 인원이 꽉찬 방 입장 시도시 alert로 꽉찼음을 알려줍니다.
> [Style] 메인화면스타일수정, 인원제한방 alert

- src/pages/MainPage/UserList.tsx
- src/pages/MainPage/UserListItem.tsx
close # 221
- 현재접속자에서 본인을 표시하는 스타일링 변경
> [Style] 현재 접속자 본인 식별

- src/pages/GamePage/GameWaitingRoom/GameRoomInfo.tsx
close #
- 게임 대기실 정보에 max Round를 추가했습니다.
> [Style] 게임 대기실 정보

- src/pages/MainPage/UserCard.tsx
close #x
- 손님이 hover시 로그인 유도메시지 카드를 보이게 하였습니다
- 닉네임 수정 버튼 대신 닉네임을 클릭하여 수정하게 하였습니다.(수정 기능은 아직 추가x)
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/87127340/74911099-d654-4591-b39f-fb36e7d9d216
> [Style] 유저 프로필 카드 스타일링

- src/pages/RankPage/RankItem.tsx
close #
- 인게임 랭킹에서 본인을 bold체와 색상으로 표시합니다
-
> [Style] 랭킹페이지 본인 표시

- src/pages/GamePage/GameSentence/utils/formatNumber.test.ts
- src/pages/GamePage/GameSentence/utils/formatNumber.ts
- src/pages/MainPage/UserCard.tsx
close #281 
- 닉네임 수정기능을 추가하였습니다
- 유저 카드에 노출되는 평균 타수, 정확도의 소숫점을 1자리로 제한하였습니다
- 위 사항을 위하여 `formatNumber`함수 및 테스트 함수 제작하였습니다
kakao redirect uri가 배포환경으로 설정 되어있어서 테스트는 해보지 못했습니다...😥
재배포 한번 해서 테스트 해야할까요?
> [Feat] 닉네임 수정기능 추가, 유저카드 소수점 절삭

- src/pages/GamePage/GameWaitingRoom/GameModeDescription.tsx
close #
- 게임 모드 설명란에 스크롤바가 생기지 않도록 수정
-
> [Style]: 게임 모드 설명 css 수정

- package.json
- src/App.tsx
- src/common/AuthRoute/AuthRoute.tsx
- src/pages/KaKaoLoginPage/KaKaoLoginPage.tsx
- src/pages/MainPage/CreateRoom/CreateRoomForm.tsx
- src/pages/NicknamePage/UpdateNickname/UpdateNicknameForm.tsx
- src/pages/StartPage/StartPage.tsx
- src/utils/storageFactory.ts
- src/utils/toast.ts
- yarn.lock
close #262 
- react-toastify를 이용하여 toast 를 적용했습니다
- success / error / info로 나누어서 토스트를 사용할 수 있습니다
https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/44563138/0a14c825-5b47-4e59-8faa-6c7d5d962ff0
- alert를 사용한 부분을 toast로 최대한 변경해봤는데 수정 못한 부분이 있을까요??
- 지금 적용한 곳 외에 더 필요한 곳이 있으면 추가해도 좋을거 같습니다!
> [Feat] Toast 적용

- .husky/pre-commit
- package.json
- src/pages/GamePage/GameSentence/GameForm.tsx
- src/pages/GamePage/GameSentence/utils/getTypo.test.ts
- vercel.json
close #293 
- 문장게임 마지막 글자 입력시 영어일때 에러를 수정하였습니다.
- 영어일때는 마지막 글자를 입력했는지 비교할때 초중종성 분리로직에 넣지 않고 비교합니다
> [🐛fix]: 마지막 글자 입력시 영어일때 에러 수정

- src/apis/api.ts
- src/apis/tokenStorage.ts
- src/common/AuthRoute/AuthRoute.tsx
- src/hooks/useAuth/useAuth.tsx
close #292 
- api.ts에서 토큰을 sessionStorage에 저장하는 함수 추가
- tokenStorage.ts 파일 추가
- AuthRoute에 Toast 메시지 삭제
- 혹시 로컬에서 간단하게 테스트해보시고 버그가 생기면 말씀해주세요..!
> [Fix]: 게스트 로그인 토큰 sessionStorage에 저장되도록 수정

- src/common/Backward/Backward.tsx
- src/utils/getToken.ts
close #296 
- 게스트로 로그인 시 방만들기가 안되는 버그를 수정했습니다
- Backward 버튼 클릭 범위가 너무 넓은 부분을 수정했습니다
- 파일 수정한 부분 매우 짧습니다..!! approave해주시면 빠르게 머지하겠습니다
> [Fix] 게임 버그 수정

- README.md
close #
- README기본 목차를 설정하였습니다.
> 리드미 기본 구조 업데이트

- README.md
> [📝docs]: Update Readme.md

- README.md
- index.html
close #
- meta description 추가 -> 구글검색에서의 description 반영 용
- 시연영상 분할 편집 한계로.. 1인화면 gif파일로 대체했습니다.
> [Docs] Update readme , GA
